 #configuration
 spring:

  datasource:
 
    #username and password from Herku
    username: bf9579c9f6e460
    password: d3c10a1b
    hikari:
      maxLifetime: 20000
      
    #Link from Herku "us-cdbr-east-06.cleardb.net"
    #3306 this is the port 
    #the name of Database on herku"heroku_3112bf82f2b0437"
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_3112bf82f2b0437
    
    

  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true     
    hibernate:
      ddl-auto: update     

 